### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by jrflemi5** [INFO-526-SU24/final-project-rahathelal#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Reagan Fleming - @jrflemi5 

- Describe the goal of the project.
The goal of this project is to understand the effectiveness of bureaucratic public policies in various countries across the world

- Describe the data used or collected.
The data used in this project consists of various economic parameters from various countries around the world. Data includes population, industrial, agricultural, and economic development benchmarks

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The question currently listed could be a bit more specific. Are there any particular indicators you are interested in exploring? Are there any countries or geographic areas you plan on taking a "deep dive" on, or are you looking at general trends across the board? This is a very large dataset and I think it would make for a more effective analysis if you were able to narrow your scope a bit.

- Is there anything that is unclear from the proposal?
I think the 2 questions should be more specific. Are we looking at agricultural development in Argentina? Workforce participation by gender in Norway? Industrial development across the globe? This is a good dataset to work with, but the project scope should be more specific.

- Provide constructive feedback on how the team might be able to improve their project.
There are a million different directions this project could take, and it would be helpful to narrow the scope to more specific questions. There are a lot of potential variables/correlations that could be analyzed, and you want to avoid a "scope creep" type of situation where you are trying to analyze too many things at once.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
I am interested in seeing the effectiveness of public policy in different regions. Some areas may be more malleable to change from outside forces depending on their culture and population.

- Provide constructive feedback on any issues with file and/or code organization.
File and code organization looks good. It would have been helpful to print a head() or summary() of the data in order to show reviewers more specific information regarding what data is actually present. Of course, we can all read code, but readability can be enhanced by printing a few rows from your tables.

- (Optional) Any further comments or feedback?
No further feedback. Best of luck with your project!

**Comment by rahathelal** [comment]
Thanks for providing your valuable feedback, I have now mentioned the two questions on employment and income group study in the proposal document. As mentioned by you, there are several factors affecting the results and it needs more research work to understand the results fully. Hence, I will be dedicating time around that too. Also, I have now added the code to display data as and when needed.
