### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by lestrada** [INFO-526-SU24/final-project-rahathelal#2]
The following is the peer review of the project proposal by Luis Estrada @lestrada #StatsForStacks

- Describe the goal of the project.
Based on the proposal write up, the goal of the project seems to explore the data as opposed to answering discrete questions. Some bits of pieces of the questions appear to be present i.e. find trends across countries. 

- Describe the data used or collected.
The data collected is from the Worldwide Bureaucracy Indicators (WWBI) database. This data is a summary of public sector employment and wages across various nations from around the world. The data set is comprised of 3 csvs: wwbi_data.csv (141985 obs of 4 variables), wwbi_series.csv (302 obs of 2 variables), wwbi_country.csv (202 obs of 29 variables).  

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
I think the right approach to starting this project is to thoroughly explore this data set and understanding it, as there are many moving parts to this data.

- Is there anything that is unclear from the proposal?
The questions that are trying to be answered are unclear to me. 

- Provide constructive feedback on how the team might be able to improve their project.
Being more specific with your goals on the data would help orient and scope the project. Because of the nature of this data, there are likely an unlimited number of ways to slice and dice the data set to try and find trends on wages. Getting more background on some of these parameters such as system_of_trade, governemt_accounting_concept etc.. can likely help understand how they impact trends. There are also likely countless interactions that are not obvious that can contribute to trends. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
I'm interested in seeing any kinds of trends on wages across different countries. 

- Provide constructive feedback on any issues with file and/or code organization.
Adding a schedule with dates would really help with priority and time management. 

- (Optional) Any further comments or feedback?
This appear to be a very challenging data set that can provide some valuable insight about global trends. Good Luck!

**Comment by rahathelal** [comment]
Thanks for providing your valuable feedback, I have now explicitly mentioned the requirements in two questions. Additionally, I have initialized the research and data analysis on the underlying datasets to come up with better answers and solutions. Also, as suggested, I would add the schedule for my final project.
