### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by derekriceX** [INFO-526-SU24/final-project-rahathelal#4]
The following is the peer review of the Presentation proposal by Derek Rice. The team members that participated in this review are 

- Derek Rice - @derekriceX 

- Content: Is the research question well designed and is the data being used relevant to the research question?

Yes the research question was well designed and focused on public sector employment changed over time and what factors influenced that change. The data used was relevant, selected datasets used to complete the analysis were from Worldwide Bureaucracy Indicators (WWBI) and included pertinent indicators. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

The presentation included three visualizations. The visualizations did not display any specific trends or statistics that would inform a data driven story, but this topic is very complex. The visualizations were interpreted correctly. 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

Yes the project was carefully thought out. Good questions were asked, informative dataset were used to complete the analysis. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

Yes - the slides were well organized, readable, included titles, and plot legends and axis title were easy to read. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

The team presented very well. The presentation was practices and delivered expertly. There was a solid introduction to the material and the visualizations were clearly explained.

**Comment by rahathelal** [comment]
Hi @derekriceX,

Thanks for your valuable feedback and suggestions. I would definitely try to improve on creating a data driven story using these datasets in future and build the visualizations accordingly. 

Thanks,
