### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by Iriscys** [INFO-526-SU24/final-project-rahathelal#6]
The following is the peer review of the Presentation proposal by Iris Sum @Iriscys . 

- Content: Is the research question well designed and is the data being used relevant to the research question?
The research question are well designed and relevant data were used to answer the questions. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes, line plot was used to visualized data changes over time, and subplots are created for different groups or factors.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
The public sector employment rate are compared and displayed from different perspectives in 3 figures. 
Just for some improvements: 
For Figure 1b, since there are not much data available for Canada, maybe can choose another countries with more years data if want to go for a comparison; 
For Figure 2, may remove NA for better presentation.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
The slides are clear and the graphs fit well. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
The presentation is well prepared and easy to follow.

**Comment by rahathelal** [comment]
Hi @Iriscys,

Thanks for your feedback and suggestions.

- I will choose another region that has data for more than one year, unfortunately I realized that North America had only these two countries in the dataset, so the current plot does not have much option. But I will check other geography and put forth the example plots somewhere in the document.
- Yes, I have now modified the plot to not show "NA" income group and that provides a better visualization. 

Thanks,
